# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'About',              url: 'about'}
- {name: 'Projects',           url: 'projects'}
- {name: 'UX Portfolio',       url: 'ux-portfolio'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', label: 'Email', link: 'mailto:t.thomas@bcbl.eu'}
- {icon: 'linkedin', label: 'LinkedIn', link: 'https://www.linkedin.com/in/trisha-thomas-a76436223/'}
- {icon: 'google', label: 'Google Scholar', link: 'https://scholar.google.com/citations?hl=en&user=aVvXJIkAAAAJ'}
#- {icon: 'rss-square', link: 'feed.xml'}
#- {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
#- {icon: 'instagram', link:  'https://instagram.com/paululele'}
#- {icon: 'envelope', link:   'mailto:hello@paulle.ca'}


# Customize site text
#pagination:
 # next_page: 'Newer'
  #previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy...'

#post_date_prefix: 'Written on'
